apiVersion: v1
kind: ServiceAccount
metadata:
  name: $ZITI_TUNNEL_SERVICE_ACCOUNT
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: $ZITI_ENROLLER_SERVICE_ACCOUNT
    labels:
      app.kubernetes.io/name: $APP_INSTANCE_NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
  name: $ZITI_ENROLLER_SERVICE_ACCOUNT
  namespace: $NAMESPACE
  ownerReferences:
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["$APP_INSTANCE_NAME-identity"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $ZITI_ENROLLER_SERVICE_ACCOUNT
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $ZITI_ENROLLER_SERVICE_ACCOUNT
subjects:
  - kind: ServiceAccount
    name: $ZITI_ENROLLER_SERVICE_ACCOUNT
    namespace: $NAMESPACE
